"""生成论文用 LaTeX 表格 -> analysis/tables/*.tex（数值全部来自 results/runs）。"""
from __future__ import annotations

import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import load as L  # noqa: E402

OUT = Path(__file__).resolve().parent / "tables"
OUT.mkdir(exist_ok=True)

SEEDS5 = [42, 123, 456, 789, 1024]
SEEDS4 = [42, 123, 456, 789]
SEEDS3 = [42, 123, 456]


def _vals(ids, key_getter):
    out = []
    for rid in ids:
        if not L.finished_ok(rid):
            continue
        v = key_getter(rid)
        if v is not None:
            out.append(v)
    return out


def _pm(vals):
    if not vals:
        return "--"
    return f"{statistics.mean(vals):.3f} $\\pm$ {statistics.pstdev(vals):.3f}"


def tab_main():
    rows = []
    for shared, label in (("high", "high"), ("low", "low")):
        for Lv in (0, 250, 1000, 4000):
            ids = [f"P1_main_{shared}_L{Lv}_s{s}" for s in SEEDS5]
            acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
            nll = _vals(ids, lambda r: L.final_c(r).get("new_task_NLL"))
            spd = _vals(ids, lambda r: L.adaptation_speed(r, 1000).get("acc_mean"))
            eb = _vals(ids, lambda r: L.end_b(r).get("acc_old_probe"))
            eh = _vals(ids, lambda r: L.end_b(r).get("acc_old_cur"))
            a2 = 0
            for rid in ids:
                hits = [x for x in L.phase_rows(rid, "B")
                        if x.get("acc_old_cur", 1) <= 0.5 and x.get("acc_old_probe", 0) >= 0.7]
                a2 += bool(hits)
            rows.append(f"{label} & {Lv} & {len(acc)} & {_pm(acc)} & {_pm(nll)} & "
                        f"{_pm(spd)} & {_pm(eh)} & {_pm(eb)} & {a2} \\\\")
    body = "\n".join(rows)
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Main sweep: terminal new-task performance and head/feature state after "
        "exposure length $L$ (mean$\\pm$std over 5 seeds). "
        "$\\mathrm{A2}$ counts seeds with at least one evaluation point satisfying "
        "head acc $\\le 0.50$ and probe acc $\\ge 0.70$.}\n"
        "\\label{tab:main}\n\\small\n"
        "\\begin{tabular}{llrcccccc}\n\\toprule\n"
        "share & $L$ & $n$ & new acc & new NLL & speed$_{1000}$ & "
        "head@endB & probe@endB & A2 \\\\\n\\midrule\n"
        f"{body}"
        "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_main.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_main.tex")


def tab_controls():
    rows = []
    groups = [("abrupt ($L{=}0$ protocol)", [f"P2_abrupt_s{s}" for s in SEEDS5]),
              ("direct (no phase A)", [f"P2_direct_s{s}" for s in SEEDS5]),
              ("headonly (frozen features)", [f"P2_headonly_s{s}" for s in SEEDS5]),
              ("head reset at switch", [f"P14_headreset_s{s}" for s in SEEDS5])]
    for Lv in (0, 250, 1000, 4000):
        groups.append((f"P1 $L{{=}}{Lv}$",
                       [f"P1_main_high_L{Lv}_s{s}" for s in SEEDS5]))
    for Lv in (0, 250, 1000):
        groups.append((f"P3 equal-budget $L{{=}}{Lv}$",
                       [f"P3_fixedc_L{Lv}_s{s}" for s in (42, 123, 456)]))
    for name, ids in groups:
        acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
        nll = _vals(ids, lambda r: L.final_c(r).get("new_task_NLL"))
        rows.append(f"{name} & {len(acc)} & {_pm(acc)} & {_pm(nll)} \\\\")
    body = "\n".join(rows)
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Controls: terminal new-task metrics for the three competing-explanation "
        "controls (E1 equal budget, E2 head-only retraining) versus the main sweep.}\n"
        "\\label{tab:controls}\n\\small\n"
        "\\begin{tabular}{llcc}\n\\toprule\n"
        "condition & $n$ & new acc & new NLL \\\\\n\\midrule\n"
        f"{body}"
        "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_controls.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_controls.tex")


def tab_transplant():
    rows = []
    groups = [("native short ($L{=}250$)", [f"P1_main_high_L250_s{s}" for s in SEEDS5]),
              ("native long ($L{=}4000$)", [f"P1_main_high_L4000_s{s}" for s in SEEDS5]),
              ("short head + long features",
               [f"P4_headShort_featLong_s{s}" for s in SEEDS5]),
              ("long head + short features",
               [f"P4_headLong_featShort_s{s}" for s in SEEDS5])]
    for name, ids in groups:
        acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
        nll = _vals(ids, lambda r: L.final_c(r).get("new_task_NLL"))
        rows.append(f"{name} & {len(acc)} & {_pm(acc)} & {_pm(nll)} \\\\")
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Cross-transplant (P4): head and features recombined across exposure "
        "lengths, then adapted to the new task.}\n"
        "\\label{tab:transplant}\n\\small\n"
        "\\begin{tabular}{lccc}\n\\toprule\n"
        "combination & $n$ & new acc & new NLL \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_transplant.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_transplant.tex")


def tab_dose():
    rows = []
    # eps -> (pattern, seeds)；1.0 用 P1（5 seeds），0.99/0.95 用 P9，0.9 用 P7
    spec = [(1.0, "P1_main_high_L{L}_s{s}", SEEDS5),
            (0.99, "P9_eps0.99_L{L}_s{s}", SEEDS3),
            (0.95, "P9_eps0.95_L{L}_s{s}", SEEDS3),
            (0.9, "P7_dose_eps0.9_L{L}_s{s}", SEEDS3),
            (0.0, "P5_diag_eps0_s{s}", SEEDS4)]
    for eps, pat, seeds in spec:
        for Lv in (250, 4000):
            if eps == 0.0:
                ids = [pat.format(s=s) for s in seeds]      # P5 只有 L=4000
                if Lv != 4000:
                    continue
            else:
                ids = [pat.format(L=Lv, s=s) for s in seeds]
            eb = _vals(ids, lambda r: L.end_b(r).get("acc_old_probe"))
            eh = _vals(ids, lambda r: L.end_b(r).get("acc_old_cur"))
            w2 = _vals(ids, lambda r: L.end_b(r).get("W2_norm"))
            acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
            if not eb:
                continue
            rows.append(f"{eps:.2g} & {Lv} & {len(eb)} & {_pm(eh)} & {_pm(eb)} & "
                        f"{_pm(w2)} & {_pm(acc)} \\\\")
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Dose--response: how much class information the exposure target "
        "still carries ($\\varepsilon=0$: continued CE; $\\varepsilon=1.0$: uniform) "
        "controls both head release and feature damage.}\n"
        "\\label{tab:dose}\n\\small\n"
        "\\begin{tabular}{llrccccc}\n\\toprule\n"
        "$\\varepsilon$ & $L$ & $n$ & head@endB & probe@endB & "
        "$\\|W_2\\|_{\\mathrm{endB}}$ & new acc \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_dose.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_dose.tex")


def tab_resnet():
    rows = []
    for Lv in (0, 250, 4000):
        ids = [f"P8_resnet_L{Lv}_s{s}" for s in SEEDS3]
        eh = _vals(ids, lambda r: L.end_b(r).get("acc_old_cur"))
        ep = _vals(ids, lambda r: L.end_b(r).get("acc_old_probe"))
        sp = _vals(ids, lambda r: L.adaptation_speed(r, 1000).get("acc_mean"))
        acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
        nll = _vals(ids, lambda r: L.final_c(r).get("new_task_NLL"))
        a2 = sum(1 for r in ids if L.finished_ok(r)
                 and any(x.get("acc_old_cur", 1) <= 0.5 and x.get("acc_old_probe", 0) >= 0.7
                         for x in L.phase_rows(r, "B")))
        rows.append(f"{Lv} & {len(acc)} & {_pm(acc)} & {_pm(nll)} & {_pm(sp)} & "
                    f"{_pm(eh)} & {_pm(ep)} & {a2} \\\\")
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{ResNet-18 (11.2M parameters) extension: the head/feature "
        "separation and the adaptation window on a larger model.}\n"
        "\\label{tab:resnet}\n\\small\n"
        "\\begin{tabular}{lrcccccc}\n\\toprule\n"
        "$L$ & $n$ & new acc & new NLL & speed$_{1000}$ & head@endB & probe@endB & A2 \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_resnet.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_resnet.tex")


def tab_det():
    """确定性核复现：同配置两份 run 的逐位一致性 + 终态 L 效应。"""
    rows = []
    for s in (42, 123):
        for Lv in (0, 250, 4000):
            a = L.metrics(f"P10_det_L{Lv}_s{s}_a")
            b = L.metrics(f"P10_det_L{Lv}_s{s}_b")
            if not a or not b or len(a) != len(b):
                rows.append(f"{s} & {Lv} & - & - \\\\")
                continue
            d = max(abs(ra.get(k, 0) - rb.get(k, 0)) for ra, rb in zip(a, b)
                    for k in ra if isinstance(ra.get(k), float))
            rows.append(f"{s} & {Lv} & {len(a)} & {d:.1e} \\\\")
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Deterministic-kernel replication (P10): two independent runs with "
        "identical configuration produce bitwise-identical metric streams "
        "(max $|\\Delta|$ over all rows), so terminal differences are no longer "
        "contaminated by process-level rerun noise.}\n"
        "\\label{tab:det}\n\\small\n"
        "\\begin{tabular}{rrrc}\n\\toprule\n"
        "seed & $L$ & rows & max $|\\Delta|$ \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_det.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_det.tex")


def tab_sensor():
    rows = []
    for Lv in (0, 500, 2000):
        ids = [f"P6_sensor_L{Lv}_s{s}" for s in SEEDS4]
        acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
        nll = _vals(ids, lambda r: L.final_c(r).get("new_task_NLL"))
        eb = _vals(ids, lambda r: L.end_b(r).get("acc_old_probe"))
        eh = _vals(ids, lambda r: L.end_b(r).get("acc_old_cur"))
        rows.append(f"{Lv} & {len(acc)} & {_pm(eh)} & {_pm(eb)} & {_pm(acc)} & {_pm(nll)} \\\\")
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Real sensor drift (UCI Gas Sensor Array Drift, batch $1\\to5$): "
        "MLP head/feature state and post-drift performance.}\n"
        "\\label{tab:sensor}\n\\small\n"
        "\\begin{tabular}{rrcccc}\n\\toprule\n"
        "$L$ & $n$ & head@endB & probe@endB & new acc & new NLL \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_sensor.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_sensor.tex")


def tab_resources():
    ids = [r["run_id"] for r in L.grid_runs() if r["block"].startswith("P")
           or r["block"] == "P7-dose"]
    walls, rss, gpu = [], [], []
    for rid in ids:
        s = L.summary(rid)
        if s.get("status") != "succeeded":
            continue
        if s.get("wall_s"):
            walls.append(s["wall_s"])
        if s.get("rss_peak_mb") and s["rss_peak_mb"] == s["rss_peak_mb"]:
            rss.append(s["rss_peak_mb"])
        if s.get("gpu_peak_mb"):
            gpu.append(s["gpu_peak_mb"])
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Measured resources over all formal runs (RTX 5060 Laptop, 8.5\\,GB).}\n"
        "\\label{tab:resources}\n\\small\n"
        "\\begin{tabular}{lcc}\n\\toprule\nmetric & value & unit \\\\\n\\midrule\n"
        f"runs measured & {len(walls)} & -- \\\\\n"
        f"wall per run (mean) & {statistics.mean(walls) if walls else float('nan'):.1f} & s \\\\\n"
        f"wall per run (max) & {max(walls) if walls else float('nan'):.1f} & s \\\\\n"
        f"peak RSS (max) & {max(rss) if rss else float('nan'):.0f} & MB \\\\\n"
        f"peak GPU mem (max) & {max(gpu) if gpu else float('nan'):.0f} & MB \\\\\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_resources.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_resources.tex")


def tab_c100():
    """CIFAR-100 外部效度：两个模型 × 三个 L。"""
    rows = []
    for model_spec in ("smallcnn", "resnet18"):
        for Lv in (0, 250, 4000):
            ids = [f"P11_c100_{model_spec}_L{Lv}_s{s}" for s in SEEDS3]
            eh = _vals(ids, lambda r: L.end_b(r).get("acc_old_cur"))
            ep = _vals(ids, lambda r: L.end_b(r).get("acc_old_probe"))
            sp = _vals(ids, lambda r: L.adaptation_speed(r, 1000).get("acc_mean"))
            acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
            nll = _vals(ids, lambda r: L.final_c(r).get("new_task_NLL"))
            ea = _vals(ids, lambda r: L.end_a(r).get("acc"))
            a2 = sum(1 for r in ids if L.finished_ok(r)
                     and any(x.get("acc_old_cur", 1) <= 0.5 and x.get("acc_old_probe", 0) >= 0.7
                             for x in L.phase_rows(r, "B")))
            rows.append(f"{model_spec} & {Lv} & {len(acc)} & {_pm(ea)} & {_pm(acc)} & "
                        f"{_pm(nll)} & {_pm(sp)} & {_pm(eh)} & {_pm(ep)} & {a2} \\\\")
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{External validity on CIFAR-100 (25 old / 25 new fine classes, "
        "official split, head slots reused): the head/feature separation and the "
        "adaptation window replicate on a harder, larger-labelspace benchmark.}\n"
        "\\label{tab:c100}\n\\small\n"
        "\\begin{tabular}{llrccccccc}\n\\toprule\n"
        "model & $L$ & $n$ & endA & new acc & new NLL & speed$_{1000}$ & "
        "head@endB & probe@endB & A2 \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_c100.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_c100.tex")


def tab_fmnist():
    """低共享臂的第二个跨域伙伴：Fashion-MNIST。"""
    rows = []
    for Lv in (0, 250, 4000):
        ids = [f"P12_fmnist_L{Lv}_s{s}" for s in SEEDS3]
        eh = _vals(ids, lambda r: L.end_b(r).get("acc_old_cur"))
        ep = _vals(ids, lambda r: L.end_b(r).get("acc_old_probe"))
        sp = _vals(ids, lambda r: L.adaptation_speed(r, 1000).get("acc_mean"))
        acc = _vals(ids, lambda r: L.final_c(r).get("new_task_acc"))
        nll = _vals(ids, lambda r: L.final_c(r).get("new_task_NLL"))
        a2 = sum(1 for r in ids if L.finished_ok(r)
                 and any(x.get("acc_old_cur", 1) <= 0.5 and x.get("acc_old_probe", 0) >= 0.7
                         for x in L.phase_rows(r, "B")))
        rows.append(f"{Lv} & {len(acc)} & {_pm(acc)} & {_pm(nll)} & {_pm(sp)} & "
                    f"{_pm(eh)} & {_pm(ep)} & {a2} \\\\")
    tex = (
        "% auto-generated by analysis/make_tables.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Second cross-domain partner for the low-sharing arm: CIFAR-10 "
        "(old) $\\to$ Fashion-MNIST (new).}\n"
        "\\label{tab:fmnist}\n\\small\n"
        "\\begin{tabular}{lrcccccc}\n\\toprule\n"
        "$L$ & $n$ & new acc & new NLL & speed$_{1000}$ & head@endB & probe@endB & A2 \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_fmnist.tex").write_text(tex, encoding="utf-8")
    print("-> tables/tab_fmnist.tex")


if __name__ == "__main__":
    tab_main(); tab_controls(); tab_transplant(); tab_dose(); tab_sensor()
    tab_resources(); tab_resnet(); tab_det(); tab_c100(); tab_fmnist()
